tinymce.addI18n('gd',{
"Redo": "Ath-dh\u00e8an",
"Undo": "Neo-dh\u00e8an",
"Cut": "Gearr \u00e0s",
"Copy": "D\u00e8an lethbhreac",
"Paste": "Cuir ann",
"Select all": "Tagh na h-uile",
"New document": "Sgr\u00ecobhainn \u00f9r",
"Ok": "Ceart ma-th\u00e0",
"Cancel": "Sguir dheth",
"Visual aids": "Taic l\u00e8irsinne",
"Bold": "Trom",
"Italic": "Eadailteach",
"Underline": "Fo-loidhne",
"Strikethrough": "Loidhne troimhe",
"Superscript": "Os-sgr\u00ecobhte",
"Subscript": "Bun-sgr\u00ecobhte",
"Clear formatting": "Falamhaich am f\u00f2rmatadh",
"Align left": "Co-thaobhaich ris an l\u00e0imh chl\u00ec",
"Align center": "Co-thaobhaich ris a' mheadhan",
"Align right": "Co-thaobhaich ris an l\u00e0imh dheas",
"Justify": "Blocaich",
"Bullet list": "Liosta pheilearaichte",
"Numbered list": "Liosta \u00e0ireamhaichte",
"Decrease indent": "Lughdaich an eag",
"Increase indent": "Meudaich an eag",
"Close": "D\u00f9in",
"Formats": "F\u00f2rmatan",
"Your browser doesn't support direct access to the clipboard. Please use the Ctrl+X/C/V keyboard shortcuts instead.": "Chan eil am brabhsair agad a' cur taic ri inntrigeadh d\u00ecreach dhan st\u00f2r-bh\u00f2rd. Cleachd ath-ghoiridean a' mheur-chl\u00e0ir, Ctrl+X/C/V 'nan \u00e0ite.",
"Headers": "Bannan-cinn",
"Header 1": "Bann-cinn 1",
"Header 2": "Bann-cinn 2",
"Header 3": "Bann-cinn 3",
"Header 4": "Bann-cinn 4",
"Header 5": "Bann-cinn 5",
"Header 6": "Bann-cinn 6",
"Headings": "Ceann-sgr\u00ecobhaidhean",
"Heading 1": "Ceann-sgr\u00ecobhadh 1",
"Heading 2": "Ceann-sgr\u00ecobhadh 2",
"Heading 3": "Ceann-sgr\u00ecobhadh 3",
"Heading 4": "Ceann-sgr\u00ecobhadh 4",
"Heading 5": "Ceann-sgr\u00ecobhadh 5",
"Heading 6": "Ceann-sgr\u00ecobhadh 6",
"Div": "Div",
"Pre": "Pre",
"Code": "C\u00f2d",
"Paragraph": "Paragraf",
"Blockquote": "Bloc-luaidh",
"Inline": "Taobh a-staigh na loidhne",
"Blocks": "Blocaichean",
"Paste is now in plain text mode. Contents will now be pasted as plain text until you toggle this option off.": "Ma chuireas tu rud ann a-nis, th\u00e8id an t-susbaint a chur ann mar theacsa lom gus an cuir thu dheth an roghainn seo a-rithist.",
"Fonts": "Cruthan-cl\u00f2",
"Font Sizes": "Meudan nan cruthan-chl\u00f2",
"Default": "Bun-roghainn",
"Circle": "Cearcall",
"Disc": "Diosga",
"Square": "Ce\u00e0rnag",
"Lower Alpha": "Aibidileach is beag",
"Lower Greek": "Litrichean Greugach beaga",
"Lower Roman": "\u00c0ireamhan R\u00f2manach is beag",
"Upper Alpha": "Aibidileach is m\u00f2r",
"Upper Roman": "\u00c0ireamhan R\u00f2manach is m\u00f2r",
"Name": "Ainm",
"You have unsaved changes are you sure you want to navigate away?": "Tha atharraichean gun s\u00e0bhaladh agad, a bheil thu cinnteach gu bheil thu airson gluasad air falbh?",
"Restore last draft": "Aisig an dreach mu dheireadh",
"Source code": "An c\u00f2d t\u00f9sail",
"Language": "C\u00e0nan",
"Color Picker": "R\u00f3ghnaichear nan dathan",
"R": "R",
"G": "G",
"B": "B",
"Left to right": "Cl\u00ec gu deas",
"Right to left": "Deas gu cl\u00ec",
"Title": "Tiotal",
"Keywords": "Faclan-luirg",
"Description": "Tuairisgeul",
"Robots": "Robotairean",
"Author": "\u00d9ghdar",
"Encoding": "C\u00f2dachadh",
"Fullscreen": "L\u00e0n-sgr\u00ecn",
"Action": "Gn\u00ecomh",
"Help": "Cobhair",
"Address": "Se\u00f2ladh",
"Horizontal line": "Loidhne ch\u00f2mhnard",
"Insert/edit image": "Cuir a-steach/Deasaich an dealbh",
"Image description": "Tuairisgeul an deilbh",
"Source": "T\u00f9s",
"Dimensions": "Meudachd",
"Constrain proportions": "Cuingich na co-r\u00e8irean",
"General": "Coitcheann",
"Advanced": "Adhartach",
"Style": "Stoidhle",
"Vertical space": "\u00c0ite inghearach",
"Horizontal space": "\u00c0ite c\u00f2mhnard",
"Border": "Iomall",
"Insert image": "Cuir a-steach dealbh",
"Rotate counterclockwise": "Cuairtich gu tuathail",
"Rotate clockwise": "Cuairtich gu deiseil",
"Flip vertically": "Thoir flip gu inghearach",
"Flip horizontally": "Thoir flip air a\u2019 ch\u00f2mhnard",
"Edit image": "Deasaich an dealbh",
"Image options": "Roghainnean an deilbh",
"Zoom in": "S\u00f9m a-steach",
"Zoom out": "S\u00f9m a-mach",
"Crop": "Bearr",
"Resize": "Atharraich am meud",
"Orientation": "Comhair",
"Brightness": "Soilleireachd",
"Sharpen": "Geuraich",
"Contrast": "Iomsgaradh",
"Color levels": "\u00ccrean nan dathan",
"Gamma": "Gamma",
"Invert": "Ais-thionndaidh",
"Apply": "Cuir an s\u00e0s",
"Back": "Air ais",
"Insert date/time": "Cuir a-steach ceann-l\u00e0/\u00e0m",
"Insert/edit link": "Cuir a-steach/Deasaich an ceangal",
"Text to display": "An teacsa a th\u00e8id a shealltainn",
"Url": "URL",
"None": "Chan eil gin",
"New window": "Uinneag \u00f9r",
"Remove link": "Thoir air falbh an ceangal",
"Anchors": "Acraichean",
"The URL you entered seems to be an email address. Do you want to add the required mailto: prefix?": "Tha coltas gu bheil an URL a chuir thu a-steach 'na she\u00f2ladh puist-d. A bheil thu airson an ro-leasachan mailto: a chur ris? Tha feum air.",
"The URL you entered seems to be an external link. Do you want to add the required http:// prefix?": "Tha coltas gu bheil an URL a chuir thu a-steach 'na cheangal ris an taobh a-muigh. A bheil thu airson an ro-leasachan http:// a chur ris? Tha feum air.",
"Insert video": "Cuir a-steach video",
"Insert/edit video": "Cuir a-steach/Deasaich a' video",
"Alternative source": "Roghainn eile de th\u00f9s",
"Paste your embed code below:": "Cuir an c\u00f2d leabachaidh agad a-steach gu h-\u00ecosal:",
"Embed": "Leabaich",
"Nonbreaking space": "Be\u00e0rn neo-bhristidh",
"Page break": "Briseadh-duilleige",
"Paste as text": "Cuir ann mar theacsa",
"Preview": "Ro-shealladh",
"Save": "S\u00e0bhail",
"Find": "Lorg",
"Replace with": "Cuir na leanas 'na \u00e0ite",
"Replace": "Cuir 'na \u00e0ite",
"Replace all": "Cuir an \u00e0ite na h-uile",
"Next": "Air adhart",
"Could not find the specified string.": "Cha b' urrainn dhuinn na dh'iarr thu a lorg.",
"Match case": "Maids litrichean m\u00f2ra 's beaga",
"Ignore": "Leig seachad",
"Ignore all": "Leig seachad na h-uile",
"Finish": "Cr\u00ecochnaich",
"Add to Dictionary": "Cuir ris an fhaclair",
"Insert table": "Cuir a-steach cl\u00e0r",
"Table properties": "Roghainnean a' chl\u00e0ir",
"Delete table": "Sguab \u00e0s an cl\u00e0r",
"Cell": "Cealla",
"Row": "R\u00e0gh",
"Column": "Colbh",
"Cell properties": "Roghainnean a' chealla",
"Merge cells": "Co-aonaich na ceallan",
"Split cell": "Sgoilt an cealla",
"Insert row before": "Cuir a-steach r\u00e0gh roimhe",
"Insert row after": "Cuir a-steach r\u00e0gh 'na dh\u00e8idh",
"Delete row": "Sguab \u00e0s an r\u00e0gh",
"Row properties": "Roghainnean an r\u00e0igh",
"Cut row": "Gearr \u00e0s an r\u00e0gh",
"Copy row": "D\u00e8an lethbhreac dhen r\u00e0gh",
"Paste row before": "Cuir ann r\u00e0gh roimhe",
"Paste row after": "Cuir ann r\u00e0gh 'na dh\u00e8idh",
"Insert column before": "Cuir a-steach colbh roimhe",
"Insert column after": "Cuir a-steach colbh 'na dh\u00e8idh",
"Delete column": "Sguab \u00e0s an colbh",
"Cols": "Colbhan",
"Rows": "R\u00e0ghan",
"Width": "Leud",
"Height": "\u00c0irde",
"Cell spacing": "Be\u00e0rnadh nan ceallan",
"Cell padding": "Padadh nan ceallan",
"Left": "Cl\u00ec",
"Center": "Meadhan",
"Right": "Deas",
"Cell type": "Se\u00f2rsa a' chealla",
"Scope": "Sg\u00f2p",
"Alignment": "Co-thaobhadh",
"H Align": "Co-thaobhadh c\u00f2mhnard",
"V Align": "Co-thaobhadh inghearach",
"Top": "Barr",
"Middle": "Meadhan",
"Bottom": "Bonn",
"Header cell": "Cealla a' bhanna-chinn",
"Row group": "Buidheann r\u00e0ghan",
"Column group": "Buidheann cholbhan",
"Row type": "Se\u00f2rsa an r\u00e0igh",
"Header": "Bann-cinn",
"Body": "Bodhaig",
"Footer": "Bann-coise",
"Border color": "Dath an iomaill",
"Templates": "Teamplaidean",
"Text color": "Dath an teacsa",
"Background color": "Dath a\u2019 ch\u00f9laibh",
"Custom...": "Gn\u00e0thaichte...",
"Custom color": "Dath gn\u00e0thaichte",
"No color": "Gun dath",
"Remove color": "Sguab \u00e0s an dath",
"Show blocks": "Seall na blocaichean",
"Show invisible characters": "Seall na caractaran do-fhaicsinneach",
"Words: {0}": "Faclan: {0}",
"File": "Faidhle",
"Edit": "Deasaich",
"Insert": "Cuir a-steach",
"View": "Sealladh",
"Format": "F\u00f2rmat",
"Table": "Cl\u00e0r",
"Tools": "Innealan",
"Rich Text Area. Press ALT-F9 for menu. Press ALT-F10 for toolbar. Press ALT-0 for help": "Raon Rich Text. Br\u00f9th ALT-F9 airson a' chl\u00e0ir-thaice. Br\u00f9th ALT-F10 airson a' bh\u00e0r-inneal. Br\u00f9th ALT-0 airson na cobharach."
});
